In [1]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
from sklearn.datasets import load_digits

In [3]:
digit=load_digits()
x=(digit.data)
y=(digit.target)

In [4]:
from sklearn.preprocessing import StandardScaler

In [5]:
x_Std=StandardScaler().fit_transform(x)

In [6]:
x_Std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [7]:
from sklearn.decomposition import PCA
pca = PCA(n_components=40)

In [8]:
principalComponents = pca.fit_transform(x_Std)

In [9]:
principalDf = pd.DataFrame(data = principalComponents)

In [10]:
principalDf

0         1         2         3         4         5         6   \
0     1.914214 -0.954502 -3.946035  2.028723 -0.267172  0.530329 -1.415323   
1     0.588980  0.924636  3.924755 -1.779851 -0.993428 -0.675649  1.878562   
2     1.302039 -0.317189  3.023333 -2.043376 -2.081153  0.935117 -1.296201   
3    -3.020770 -0.868772 -0.801745 -2.187040 -0.556808  0.727121  0.959763   
4     4.528949 -1.093480  0.973121 -1.419510 -1.715107  1.431598  1.073648   
5    -1.301890 -1.148183 -1.574607 -2.413648 -0.630978  0.740809  1.306797   
6     1.434222 -2.957845  2.831278 -0.076952  0.523031  0.010907  0.983718   
7     0.614240  5.462184  0.658242  0.434430  0.850170 -0.954017 -1.833863   
8    -1.098451 -0.665823 -0.041023 -1.102526 -0.900721  0.755126 -0.966466   
9    -0.537970 -0.777493 -1.568922 -0.759983 -0.121341 -0.600999  0.675190   
10    3.378760 -0.495768 -2.280895  1.429204  0.006569 -0.150573 -0.739177   
11    2.063345  2.016679  1.540476 -4.773150 -2.194263  0.344452  3.084412   
12   -1.937011 -1.815247  2.801367 -0.786548  3.025777 -0.384549 -0.647719   
13   -3.258077  2.149124 -1.615648 -1.798928 -0.745367  1.828834  0.763419   
14    5.458744  0.025132  0.182527 -0.119622 -0.541033  0.104818  1.083111   
15   -3.877036  2.606816  1.858528  5.454026  0.615483  0.988483  3.602248   
16    0.921351 -3.262241  3.401443 -3.227337  1.096490  0.081974 -0.573138   
17    1.415335  1.954479  0.560574 -0.368825 -1.302537 -1.883609 -1.063239   
18   -0.926522  2.253018  1.532929  0.111959 -1.640292  0.261409 -0.069194   
19   -2.370963 -2.931915 -0.381362 -3.232762  2.084194  0.545304 -0.615775   
20    2.001901 -1.319746 -2.570949  0.855346 -0.565534 -1.017702 -0.812000   
21    1.694878  2.075387  0.885988 -4.388595 -1.446103 -0.307276  3.643107   
22   -3.114571 -1.058976  2.451496 -0.547892  0.761751 -0.012647 -1.890064   
23   -1.469418  3.910389 -2.078331 -0.869924  0.203791  0.689529 -0.288164   
24    4.003333 -0.322216  0.587683 -2.740555 -1.513548  0.676051  2.088573   
25   -0.376722  0.525118  1.356042  3.106104  0.926274 -1.029455  1.450078   
26    1.286726 -3.969443  2.542968  0.936671  0.282391  0.352663  1.026767   
27    3.842317  3.478237 -1.569506 -1.675844 -0.274119 -0.345098 -0.150006   
28   -0.166537  0.934112  1.259154 -0.086537 -1.045700  0.362898 -0.877876   
29   -2.014425 -2.376845 -0.707906 -3.515254  1.168346  0.694467  0.206819   
...        ...       ...       ...       ...       ...       ...       ...   
1767  4.958573 -1.159637  0.645671 -1.495314 -1.408076  0.580227  2.222101   
1768  1.009034 -3.325935 -0.584416  0.907491 -0.665940  0.398985 -1.279989   
1769 -0.542840 -0.492983 -3.138879  0.952805  0.732339 -1.169263  1.900085   
1770 -3.314656  1.510568 -0.820052 -1.838159 -1.474756  1.442511  2.178238   
1771  2.128214 -2.822365  3.623384 -1.087841 -0.085811  0.389346  1.443189   
1772 -1.814030  1.197999 -3.113638 -1.063801 -1.806721  0.021177  1.294920   
1773  1.374678 -4.417769  0.544578  0.931147  1.151818 -0.342561  0.125667   
1774  0.762953  0.643399  3.119026 -0.449233 -2.038234 -0.268291 -0.225330   
1775 -0.433045  3.216018  2.011168 -0.229288 -1.509359 -1.166802 -2.852443   
1776 -0.525867 -1.154642 -1.889820  0.953331  0.807080 -1.084717  1.495884   
1777  5.106682 -0.289142  0.341407 -1.773523 -2.469450  1.596727  0.885047   
1778  5.900098 -1.710240  1.858915  0.171253 -4.529244  4.714797  0.440309   
1779  1.597139  4.676427  0.469293 -0.503398 -0.074208 -1.780283 -2.551041   
1780 -5.137834 -0.191049  2.223967  2.046425 -0.885013  3.406914 -0.342171   
1781 -1.416098 -1.031485  1.196077  0.841545 -2.197928  2.483205  0.573300   
1782 -4.272989 -1.355840  3.059713  0.367666  1.045038  0.747238  0.006423   
1783 -3.136887 -1.411700  2.238424 -0.085145  0.779782  0.689965 -1.289869   
1784  1.568544 -0.438603 -1.840596 -0.847230  0.413575 -1.193732  2.474062   
1785  0.058277  1.978137  1.807599  1.282992 -1.856850 -0.847035 -3.167595   
1786 -0.711454  0.253346 -2.934788

In [11]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932003,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914167, 0.01775547, 0.01638069, 0.0159646 , 0.01489191,
       0.01347969, 0.01271931, 0.01165837, 0.01057646, 0.00975314,
       0.00944554, 0.00863012, 0.00836632, 0.0079769 , 0.00746457,
       0.00725539, 0.00691882, 0.00653899, 0.00640778, 0.00591367,
       0.00570883, 0.00523382, 0.00481557, 0.00452548, 0.00422214])

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
principalDf_train,principalDf_test,y_train,y_test = train_test_split(principalDf,y,test_size = 0.3)

In [14]:
model=LogisticRegression()
model.fit(principalDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
pred=model.predict(principalDf_test)
pred

array([7, 6, 3, 2, 7, 2, 9, 6, 8, 7, 8, 6, 7, 0, 7, 2, 6, 0, 6, 2, 6, 4,
       5, 6, 3, 4, 6, 1, 1, 7, 4, 3, 6, 3, 7, 0, 3, 1, 5, 1, 2, 0, 2, 4,
       4, 4, 6, 1, 7, 7, 4, 5, 1, 1, 1, 5, 2, 4, 0, 4, 9, 1, 4, 9, 9, 6,
       8, 8, 8, 7, 4, 8, 8, 5, 9, 1, 9, 4, 3, 4, 4, 6, 4, 6, 5, 3, 7, 3,
       2, 3, 1, 1, 9, 5, 8, 8, 7, 5, 2, 6, 2, 3, 7, 7, 9, 5, 1, 9, 6, 5,
       4, 4, 4, 4, 1, 3, 8, 5, 7, 9, 2, 3, 8, 8, 8, 6, 4, 4, 2, 6, 2, 7,
       5, 2, 2, 1, 4, 8, 2, 3, 2, 7, 2, 8, 3, 9, 4, 0, 9, 3, 1, 1, 1, 8,
       1, 5, 3, 8, 7, 2, 9, 9, 8, 6, 6, 1, 3, 5, 4, 0, 7, 3, 6, 7, 2, 9,
       5, 1, 3, 7, 0, 5, 4, 7, 2, 4, 2, 5, 6, 3, 4, 1, 0, 6, 2, 3, 5, 8,
       4, 4, 3, 7, 7, 4, 3, 9, 6, 1, 2, 7, 1, 7, 2, 2, 2, 3, 3, 1, 6, 7,
       8, 0, 2, 7, 2, 5, 5, 4, 9, 4, 0, 6, 3, 1, 9, 7, 0, 6, 6, 7, 8, 0,
       0, 4, 3, 5, 8, 8, 9, 2, 4, 3, 9, 0, 5, 3, 0, 5, 4, 9, 7, 0, 2, 3,
       5, 1, 1, 0, 8, 2, 5, 2, 4, 6, 3, 3, 8, 7, 0, 0, 7, 5, 7, 8, 9, 9,
       6, 3, 0, 8, 8, 1, 7, 0, 1, 6, 7, 5, 1, 0, 1,

In [16]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.9592592592592593

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        50
          1       0.95      0.95      0.95        56
          2       0.96      1.00      0.98        54
          3       0.96      0.92      0.94        53
          4       0.98      0.97      0.98        61
          5       0.87      0.94      0.90        50
          6       0.98      0.98      0.98        55
          7       1.00      0.98      0.99        63
          8       0.96      0.88      0.92        52
          9       0.92      0.96      0.94        46

avg / total       0.96      0.96      0.96       540



In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
confusion_matrix(y_test,pred)

array([[50,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 53,  1,  0,  0,  0,  1,  0,  1,  0],
       [ 0,  0, 54,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 49,  0,  3,  0,  0,  1,  0],
       [ 0,  0,  0,  0, 59,  0,  0,  0,  0,  2],
       [ 0,  0,  0,  1,  0, 47,  0,  0,  0,  2],
       [ 0,  1,  0,  0,  0,  0, 54,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 62,  0,  0],
       [ 0,  1,  1,  1,  0,  3,  0,  0, 46,  0],
       [ 0,  1,  0,  0,  0,  1,  0,  0,  0, 44]])